{% set name = "hide_code" %}
{% set version = "0.6.0" %}
{% set sha256 = "73d7ff058cf5637b47af9504cbbd8bdb9e6e256668ccceeb425865fd50616335" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/h/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  skip: true  # [win or osx or py < 30]
  script: |
    set -ex
    python setup.py install --single-version-externally-managed --record record.txt
    jupyter nbextension install --py hide_code --sys-prefix

requirements:
  host:
    - python
    - setuptools
    - notebook >=4.4.1
    - python-pdfkit
  run:
    - python
    - notebook >=4.4.1
    - python-pdfkit

test:
  imports:
    - hide_code

about:
  home: https://github.com/kirbs-/hide_code
  license: MIT
  license_file: hide_code/LICENSE
  summary: Code, prompt and output hiding for Jupyter/IPython notebooks.

extra:
  recipe-maintainers:
    - scopatz
