appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: NaaC/GCRZVOx9BlEbUUiPrBpiJlj4O8C0X4ZrkNfcVIaNOmeUst8AYKlWPoIG7LdzZJPSCN52HWa0HjkMuE6M+gYBF9fStTPhR2elN8DGOq4qATETpN4mIEquDTphdQ7/ksgqk2DO+HUBKahbArCKca378f1cIBsHGf07LpotgC5X51GBtWrPeftt8T+9rlUgvOXuR003VYn6Sxhr8b9doOHPzV4SLzzLDanZ0ZiKSdBt5vmMhDea95HTdccAXX/ZS0eBSsewm8vAB5KkcDdZXNIM9GD5mwka5fKmvEeL8ytUnRDm/THPCNurorUy8H8Xt9GOY+HSDW82zha70sAx0JnptUEjOdYh9wsNJvCW74inof2v7h2DCjPigZ+zAWylp2EJT0/22j79ezfaHrmPShuow7/+TXZJ0lvV02uY757Ng0MAIr9BUSfYAwbPC1C8LTvThOE9zoRS0Q3j0uN1LHicMgqndZf7hvwr52CaAdZnBSApJq0gtmyyreDwskxl7pJXwV/znfivR08usnKHy6aFMCf+Ev6Yu50I1TE0cNS3WjI3Re6px2H47x0LwwuZbu9RYWWlDn0JEeW9DSSsvzW8mTZ7nhxMso9YQcYW+pEKtQH2rfzlg+7nSfX2qpo5jS8M7t71Pt7XOejRR0XIgaa3nc6w2Sra0K2+jQBCYs=}
